### ISSUE TITLE
error when deleteblocks

### ISSUE THREAD

**Issue by berengma** [random-geek/MapEdit#1]
` python3.7 mapedit.py -f map.sqlite --p1 100 -100 100 --p2 -100 100 -100 deleteblocks
WARNING: Using this tool can potentially cause permanent
damage to your map database. Please SHUT DOWN the game/server
and BACK UP the map before proceeding. To continue this
operation, type 'yes'.
> yes
Traceback (most recent call last):
  File "mapedit.py", line 177, in <module>
    args.func(db, args)
  File "/Jungle/lib/commands.py", line 50, in delete_blocks
    list = helpers.get_mapblocks(cursor, area=(p1, p2), inverse=args.inverse)
NameError: name 'cursor' is not defined
`

line 50 says cursor, but it seems not to be defined. 
i replaced "cursor" by "database" and now code is not interrupted and runs. But I am not sure if it really does what it should, because mapsize does not change after mapblocks have been deleted.

**Comment by random-geek** [comment]
Should be fixed now.
